# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'insurance.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MyInsurance(object):
    def __init__(self, age, bmi, sex, children, smoker, region, price):
        self.age = None
        self.bmi = None
        self.sex = None
        self.children = None
        self.smoker = None
        self.region = None
        self.price = None
    def get_age(self):
        self.age = self.age_text.text()
        self.age = int(self.age) if self.age.isdigit() else None
        return self.age
    
    def get_bmi(self):
        self.bmi = self.bmi_text.text()
        self.bmi = float(self.bmi) if self.bmi.replace('.', '', 1).isdigit() else None
        return self.bmi
    
    def get_sex(self, sexButton):
        if sexButton.text() == 'Female':
            self.sex = 0
            return self.sex
        elif sexButton.text() == 'Male':
            self.sex = 1
            return self.sex
        else:
            self.display_price.setText("Please select your sex.")        
    
    def get_children(self):
        self.children = self.NumOfChildren.value()
        return self.children
        
    def get_smoker(self):
        self.smoker = 1
        return self.smoker
    
    def get_region(self, regionButton):
        if regionButton.text() == 'Northeast':
            self.region = [0, 0, 0]
            return self.region
        elif regionButton.text() == 'Southeast':
            self.region = [0, 1, 0]
            return self.region
        elif regionButton.text() == 'Northwest':
            self.region = [1, 0, 0]
            return self.region
        elif regionButton.text() == 'Southwest':
            self.region = [0, 0, 1]
            return self.region
        
    def setupUi(self, MyInsurance):
        MyInsurance.setObjectName("MyInsurance")
        MyInsurance.resize(450, 600)
        self.centralwidget = QtWidgets.QWidget(MyInsurance)
        self.centralwidget.setObjectName("centralwidget")
        self.MaleButton = QtWidgets.QRadioButton(self.centralwidget)
        self.MaleButton.setGeometry(QtCore.QRect(245, 210, 51, 17))
        self.MaleButton.setObjectName("MaleButton")
        self.genderbuttonsgroup = QtWidgets.QButtonGroup(MyInsurance)
        self.genderbuttonsgroup.setObjectName("genderbuttonsgroup")
        self.genderbuttonsgroup.addButton(self.MaleButton)
        self.FemaleButton = QtWidgets.QRadioButton(self.centralwidget)
        self.FemaleButton.setGeometry(QtCore.QRect(115, 210, 61, 17))
        self.FemaleButton.setObjectName("FemaleButton")
        self.genderbuttonsgroup.addButton(self.FemaleButton)
        self.NumOfChildren = QtWidgets.QSpinBox(self.centralwidget)
        self.NumOfChildren.setGeometry(QtCore.QRect(180, 270, 71, 22))
        self.NumOfChildren.setObjectName("NumOfChildren")
        self.regionNth = QtWidgets.QRadioButton(self.centralwidget)
        self.regionNth.setGeometry(QtCore.QRect(235, 390, 82, 17))
        self.regionNth.setObjectName("regionNth")
        self.regionButtonsGroup = QtWidgets.QButtonGroup(MyInsurance)
        self.regionButtonsGroup.setObjectName("regionButtonsGroup")
        self.regionButtonsGroup.addButton(self.regionNth)
        self.regionSth = QtWidgets.QRadioButton(self.centralwidget)
        self.regionSth.setGeometry(QtCore.QRect(235, 420, 82, 17))
        self.regionSth.setObjectName("regionSth")
        self.regionButtonsGroup.addButton(self.regionSth)
        self.bmitext = QtWidgets.QLabel(self.centralwidget)
        self.bmitext.setGeometry(QtCore.QRect(200, 130, 161, 20))
        self.bmitext.setObjectName("bmitext")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 50, 201, 20))
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.display_price = QtWidgets.QTextBrowser(self.centralwidget)
        self.display_price.setGeometry(QtCore.QRect(105, 520, 221, 31))
        self.display_price.setObjectName("display_price")
        self.Price_label = QtWidgets.QLabel(self.centralwidget)
        self.Price_label.setGeometry(QtCore.QRect(197, 500, 61, 20))
        self.Price_label.setObjectName("Price_label")
        self.user_children = QtWidgets.QLabel(self.centralwidget)
        self.user_children.setGeometry(QtCore.QRect(190, 240, 47, 21))
        self.user_children.setObjectName("user_children")
        self.user_gender = QtWidgets.QLabel(self.centralwidget)
        self.user_gender.setGeometry(QtCore.QRect(190, 190, 61, 16))
        self.user_gender.setObjectName("user_gender")
        self.user_Smoker = QtWidgets.QLabel(self.centralwidget)
        self.user_Smoker.setGeometry(QtCore.QRect(190, 310, 47, 13))
        self.user_Smoker.setObjectName("user_Smoker")
        self.isSmoker = QtWidgets.QCheckBox(self.centralwidget)
        self.isSmoker.setGeometry(QtCore.QRect(190, 330, 41, 17))
        self.isSmoker.setObjectName("isSmoker")
        self.user_region = QtWidgets.QLabel(self.centralwidget)
        self.user_region.setGeometry(QtCore.QRect(190, 340, 71, 61))
        self.user_region.setObjectName("user_region")
        self.sender = QtWidgets.QPushButton(self.centralwidget)
        self.sender.setGeometry(QtCore.QRect(170, 470, 81, 23))
        self.sender.setCheckable(True)
        self.sender.setObjectName("sender")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 230, 471, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 170, 471, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(0, 110, 471, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(0, 20, 471, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(0, 290, 471, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(0, 350, 471, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(0, 450, 471, 20))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.age_text = QtWidgets.QLineEdit(self.centralwidget)
        self.age_text.setGeometry(QtCore.QRect(160, 70, 113, 20))
        self.age_text.setText("")
        self.age_text.setObjectName("age_text")
        self.bmi_text = QtWidgets.QLineEdit(self.centralwidget)
        self.bmi_text.setGeometry(QtCore.QRect(160, 150, 113, 20))
        self.bmi_text.setText("")
        self.bmi_text.setObjectName("bmi_text")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(131, 0, 191, 21))
        self.textBrowser.setStyleSheet("border: none;")
        self.textBrowser.setObjectName("textBrowser")
        self.regionNTHW = QtWidgets.QRadioButton(self.centralwidget)
        self.regionNTHW.setGeometry(QtCore.QRect(110, 390, 82, 17))
        self.regionNTHW.setObjectName("regionNTHW")
        self.regionButtonsGroup.addButton(self.regionNTHW)
        self.regionSTHW = QtWidgets.QRadioButton(self.centralwidget)
        self.regionSTHW.setGeometry(QtCore.QRect(110, 420, 82, 17))
        self.regionSTHW.setObjectName("regionSTHW")
        self.regionButtonsGroup.addButton(self.regionSTHW)
        MyInsurance.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MyInsurance)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 473, 21))
        self.menubar.setObjectName("menubar")
        MyInsurance.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MyInsurance)
        self.statusbar.setObjectName("statusbar")
        MyInsurance.setStatusBar(self.statusbar)

        self.FemaleButton.toggled.connect(lambda checked: self.get_sex(sexButton=self.FemaleButton))
        self.MaleButton.toggled.connect(lambda checked: self.get_sex(sexButton=self.MaleButton))

        self.regionNTHW.toggled.connect(lambda checked: self.get_region(regionButton=self.regionNTHW))
        self.regionSTHW.toggled.connect(lambda checked: self.get_region(regionButton=self.regionSTHW))
        self.regionNth.toggled.connect(lambda checked: self.get_region(regionButton=self.regionNth))
        self.regionSth.toggled.connect(lambda checked: self.get_region(regionButton=self.regionSth))
        
        self.retranslateUi(MyInsurance)
        QtCore.QMetaObject.connectSlotsByName(MyInsurance)

    def retranslateUi(self, MyInsurance):
        _translate = QtCore.QCoreApplication.translate
        MyInsurance.setWindowTitle(_translate("MyInsurance", "MyInsrurance"))
        self.MaleButton.setText(_translate("MyInsurance", "Male"))
        self.FemaleButton.setText(_translate("MyInsurance", "Female"))
        self.regionNth.setText(_translate("MyInsurance", "Northeast"))
        self.regionSth.setText(_translate("MyInsurance", "Southeast"))
        self.bmitext.setText(_translate("MyInsurance", "BMI"))
        self.label.setText(_translate("MyInsurance", "Age"))
        self.display_price.setHtml(_translate("MyInsurance", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Price_label.setText(_translate("MyInsurance", "Price"))
        self.user_children.setText(_translate("MyInsurance", "Children"))
        self.user_gender.setText(_translate("MyInsurance", "Gender"))
        self.user_Smoker.setText(_translate("MyInsurance", "Smoker"))
        self.isSmoker.setText(_translate("MyInsurance", "Yes"))
        self.user_region.setText(_translate("MyInsurance", "Region"))
        self.sender.setText(_translate("MyInsurance", "Send"))
        self.textBrowser.setHtml(_translate("MyInsurance", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; font-style:italic; color:#aa00ff;\">Insurance Quote Calculator</span></p></body></html>"))
        self.regionNTHW.setText(_translate("MyInsurance", "Northwest"))
        self.regionSTHW.setText(_translate("MyInsurance", "Southwest"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MyInsurance = QtWidgets.QMainWindow()
    ui = Ui_MyInsurance()
    ui.setupUi(MyInsurance)
    MyInsurance.show()
    sys.exit(app.exec_())
